### ISSUE TITLE
Discussion and Progress for v1 Release

### ISSUE THREAD

**Issue by emsifa** [rakit/validation#63]
Beforehand, I want to say thank you for your contributions and inputs so far :bowing_man: 

I wanna make some major changes to this package based on previous issues and my experience. 
But actually, I've rarely used PHP lately, especially this package. 
And because it would be a `v1` (stable release), I want to implement best practices to our codes. 
So I need your inputs and suggestions to do this.

So far, this is my to-do lists for `v1`:

- [x]  Drop support for PHP 5. Minimum support is PHP 7.0.  #62 
- [x] Change `ErrorBag::firstOrAll` to return array assoc instead of indexed array. #64 
- [x] ~~Split `uploaded_file` rule to `uploaded_filesize` and `uploaded_filetype` so we get separate error message~~. Add `mimes` to validate uploaded file mimes, and update `min`, `max`, and `between` rules to be able to validate uploaded file size. #69 
- [x] Adding doc comments to methods and properties. #67 
- [x] Adding type hint and return type. #67 
- [x] Fixing some inconsistency in variable naming and format. #66 
- [x] Improve documentation. #70 #72 
- [x] Support multiple file upload. #71 

And as I'm not fluent in English. Any misspelled correction in the documentation would be appreciated.

I have created branch `v1` for this release. So we can make some PR to that branch. And start from now, only bugfixes are allowed to merged to master. Any other minor changes would be merged to v1. I will merge `v1` to `master` after we have done those to-do lists.

Thank you.

**Comment by peter279k** [comment]
Hi @emsifa, thank you for your reply.

I appreciate your help.

I have some problems about the TODO lists:

> Fixing some inconsistency in variable naming and format.
What's the inconsistency variable naming and format?

Can you mention that?

Thanks.

**Comment by emsifa** [comment]
@peter279k some variables and properties using `snake_case` format, while some others using `camelCase` format. 

For example:
https://github.com/rakit/validation/blob/064f3ac12bbb854841b2d44dffcc554a813c18b3/src/Attribute.php#L36 
and 
https://github.com/rakit/validation/blob/064f3ac12bbb854841b2d44dffcc554a813c18b3/src/Rule.php#L19.

I think we should generalize all using `camelCase` format as commonly used in other libraries and frameworks.

**Comment by peter279k** [comment]
@emsifa, thank you for your reply.

I think we need to concern the [PSR-2](https://www.php-fig.org/psr/psr-2/) coding style.

And we can use the `camelCase` format for this source code.

BTW, we also can integrate the `PHP_CodeSniffer` or `php-cs-fixer` to do this.

**Comment by emsifa** [comment]
@peter279k Ah that is what I want. Can you integrate `PHP_CodeSniffer` to this repository? I'm gonna make other changes later.

**Comment by peter279k** [comment]
Hi @emsifa, I will do that :).

**Comment by peter279k** [comment]
Hi @emsifa, which approach that you prefer about adding `type hint`?

I found that it has the two different way about `type hint` in this source code.

One is `PHPDoc` style, and another one is add `type hint` directly for every methods.

**Comment by peter279k** [comment]
@emsifa, thank you for your reply.

I think it's fine to do both of these.

**Comment by peter279k** [comment]
Hi @emsifa, the final work is about splitting the `UploadedFile` class to two classes.

Do you have the plan to do that? Thanks.

**Comment by emsifa** [comment]
Hi @peter279k, yes I will work for that tomorrow on weekend. After that I need to update some documentation before release it.

**Comment by emsifa** [comment]
`v1.0.0` just released. And I deleted `v1` branch to avoid someone merge to that branch. 

Thank you. :smiley:
